#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.


echo "Copying database config from .openshift/config"
cp $OPENSHIFT_REPO_DIR/.openshift/config/database.php $OPENSHIFT_REPO_DIR/app/config/database.php 2>/dev/null
